config/routes.rb
SampleApp::Application.routes.draw do

  resources :users  do
    collection do
      get :activate_email        # have used get because other methods are not working...bcos the activation email source html in gmail doesn't show data-method='put'..maybe the rails javascript doesnt work in gmail...gotta verify this shit
    end
    member do
       get :following,:followers
     end
  end

  resources :sessions, only:[:new, :create, :destroy]
  resources :microposts, only:[:create,:destroy]
  resources :relationships, only: [:create,:destroy]
  resources :password_resets
  root to: 'static_pages#home'

  match '/signup', to:'users#new'
  match '/signin', to:'sessions#new'
  match '/signout', to:'sessions#destroy', via: :delete
  match '/help', to: 'static_pages#help'
match '/about', to: 'static_pages#about'
match '/contact', to: 'static_pages#contact'

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    user.send_password_reset if user
    redirect_to root_url, notice: "Email sent with password reset instructions"
  end

  def edit
    @user = User.find_by_password_reset_token(params[:id])
  end

  def update
    @user = User.find_by_password_reset_token(params[:id])
    if @user.password_reset_sent_at < 2.hours.ago
    redirect_to  new_password_reset_path, alert:"Password reset has expired"
    elsif @user.update_attributes(params[:user])
      redirect_to root_path , notice: "Password has been reset"
    else
      render :edit
    end
  end

end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide(:title, "Reset password") %>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
      <%= render "shared/error_messages", object: f.object %>
    <%= f.label :password %>
    <%= f.text_field :password %>
    <%= f.label :password_confirmation %>
    <%= f.text_field :password_confirmation %>
    <%= f.submit "Reset password", class:"btn btn-large btn-primary" %>
    <% end %>
   </div>
</div>

app/views/password_resets/new.html.erb
<% provide(:title, "Reset password") %>
<div class="row">
  <div class="span6 offset3">
<%= form_tag password_resets_path, :method => :post do %>
    <div class="field">
      <%= label_tag :email %>
      <%= text_field_tag :email, params[:email] %>
    </div>
    <div class="actions"><%= submit_tag "Reset password" %></div>
<% end %>
      </div>
    </div>